version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mobilya_postgres
    environment:
      POSTGRES_DB: furniture_db
      POSTGRES_USER: furniture_user
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U furniture_user -d furniture_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mobilya_backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  db_data: